### ISSUE TITLE
Stub generator produces invalid Rust code for `loop N+1`

### ISSUE THREAD

**Issue by Andriamanitra** [Andriamanitra/clash#53]
**Describe the bug**
Stub generator for Rust can produce invalid code when a variable is used in an arithmetic expression describing the number of times to loop. This is because in the expression `n+1 as usize` the `as usize` cast only applies to `1` instead of `n+1`.

**To Reproduce**
```console
$ printf "read N:int\nloop N+1 write N\n" | clash generate-stub rust --from-file -
use std::io;

macro_rules! parse_input {
    ($x:expr, $t:ident) => ($x.trim().parse::<$t>().unwrap())
}
fn main() {
    let mut input_line = String::new();
    io::stdin().read_line(&mut input_line).unwrap();
    let n = parse_input!(input_line, i32);
    for i in 0..n+1 as usize {
        println!("N");
    }
}

$ printf "read N:int\nloop N+1 write N\n" | clash generate-stub rust --from-file - | rustc --emit=metadata -
error[E0308]: mismatched types
  --> <anon>:10:19
   |
10 |     for i in 0..n+1 as usize {
   |                   ^^^^^^^^^^ expected `i32`, found `usize`
```

**Expected behavior**
We could add parens like `(n+1) as usize`. Another option would be `n as usize + 1`.

**Comment by daxida** [comment]
```
Expected behavior
CodinGame adds parens like (n+1) as usize.
```

This is not true, CG does the same and as such the stub also crashes in the IDE

![image](https://github.com/Andriamanitra/clash/assets/80173028/92557a7f-e838-476d-9d0f-aa7d8a2cb772)
![image](https://github.com/Andriamanitra/clash/assets/80173028/3583208d-b524-4e9d-92a4-909717a4421f)

This is a hack (and a dirty one), that even crashes their stub before entering the IDE (and I'm not even sure why it ends up working).

You can test it yourself:

- Go to the clash: https://www.codingame.com/contribute/view/5983c5ceedd8425e2617a5a482095ca77a25
- Click the edit button
- Click go to IDE on the bottom right
- Confirm the message error that says that the stub crashed because it looked for a variable called "N+1" (and not "N" + 1)

![image](https://github.com/Andriamanitra/clash/assets/80173028/f377151c-3338-4ccb-9559-5599b1f38f87)

**Comment by Andriamanitra** [comment]
> ```
> Expected behavior
> CodinGame adds parens like (n+1) as usize.
> ```
> 
> This is not true, CG does the same and as such the stub also crashes in the IDE

Oops you're right. I've edited the issue description.

**Comment by Andriamanitra** [comment]
Turns out it's no longer possible to create clashes with `loop N+1` so this problem only happened with one legacy clash which is now fixed.
